"""Add pipeline_runs, pipeline_steps, and artifacts tables for Sprint 2

Revision ID: d737e2bdb6ed
Revises: ce3f7b59319e
Create Date: 2025-12-24 13:40:21.044263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd737e2bdb6ed'
down_revision: Union[str, Sequence[str], None] = 'ce3f7b59319e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
